spring:
  datasource:
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8048
api:
  crossorigin: http://localhost:4200
  uri: /api/